/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeaderAppHeader: typeof import('./components/AppHeader/AppHeader.vue')['default']
    MatchCard: typeof import('./components/Match/Card.vue')['default']
    MatchDeck: typeof import('./components/Match/Deck.vue')['default']
    MatchLakeStack: typeof import('./components/Match/LakeStack.vue')['default']
    MatchMatchBoard: typeof import('./components/Match/MatchBoard.vue')['default']
    MatchNertsPile: typeof import('./components/Match/NertsPile.vue')['default']
    MatchPlayingCard: typeof import('./components/Match/PlayingCard.vue')['default']
    MatchRiverStack: typeof import('./components/Match/RiverStack.vue')['default']
    MatchStack: typeof import('./components/Match/Stack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UtilsAppHeaderButton: typeof import('./components/Utils/AppHeaderButton.vue')['default']
    UtilsButton: typeof import('./components/Utils/Button.vue')['default']
    UtilsCard: typeof import('./components/Utils/Card.vue')['default']
  }
}
